# Generated by Django 5.0.6 on 2026-05-27 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(default='GB', max_length=2)),
                ('grid_region', models.CharField(default='UK', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=64)),
                ('activity_key', models.CharField(db_index=True, max_length=128)),
                ('unit', models.CharField(max_length=32)),
                ('factor', models.DecimalField(decimal_places=6, max_digits=14)),
                ('factor_unit', models.CharField(default='kgCO2e', max_length=64)),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
                ('source', models.CharField(default='DEFRA 2023', max_length=128)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['activity_key', 'valid_from'], name='emissions_e_activit_4a0fa8_idx')],
            },
        ),
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP_FUEL', 'SAP fuel movements'), ('UTILITY_ELEC', 'Utility electricity'), ('TRAVEL', 'Corporate travel')], max_length=20)),
                ('filename', models.CharField(max_length=256)),
                ('file_hash', models.CharField(db_index=True, max_length=64)),
                ('row_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('parse_errors', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('locked', 'Locked')], default='processing', max_length=16)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_batches', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='emissions.tenant')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
                ('category', models.CharField(db_index=True, max_length=64)),
                ('activity_start', models.DateField()),
                ('activity_end', models.DateField()),
                ('quantity_raw', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit_raw', models.CharField(max_length=32)),
                ('quantity_normalized', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit_normalized', models.CharField(max_length=32)),
                ('co2e_kg', models.DecimalField(decimal_places=4, max_digits=18)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('flagged', 'Flagged'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked')], default='pending', max_length=16)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('review_note', models.TextField(blank=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emission_factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='emissions.emissionfactor')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emissions.facility')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emissions', to='emissions.ingestionbatch')),
            ],
            options={
                'ordering': ['-activity_start'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('status_change', 'Status change'), ('edited', 'Edited'), ('flagged', 'Flagged'), ('batch_locked', 'Batch locked')], max_length=32)),
                ('before_value', models.JSONField(blank=True, null=True)),
                ('after_value', models.JSONField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('emission_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='emissions.emissionrecord')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='emissions.ingestionbatch')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row_number', models.IntegerField()),
                ('raw_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='emissions.ingestionbatch')),
            ],
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='raw_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emission', to='emissions.rawrecord'),
        ),
        migrations.CreateModel(
            name='PlantCodeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_code', models.CharField(max_length=8)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_codes', to='emissions.facility')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_codes', to='emissions.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='facility',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='emissions.tenant'),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emissions', to='emissions.tenant'),
        ),
        migrations.AddIndex(
            model_name='rawrecord',
            index=models.Index(fields=['batch', 'source_row_number'], name='emissions_r_batch_i_d9dd75_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='plantcodemapping',
            unique_together={('tenant', 'plant_code')},
        ),
        migrations.AlterUniqueTogether(
            name='ingestionbatch',
            unique_together={('tenant', 'file_hash')},
        ),
        migrations.AlterUniqueTogether(
            name='facility',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant', 'scope', 'activity_start'], name='emissions_e_tenant__b7a038_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['status'], name='emissions_e_status_035f31_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['category'], name='emissions_e_categor_11b7d7_idx'),
        ),
    ]
